// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZClBjWbnkRa42reszgmFenQLyR04Fxys',
    appId: '1:766431108730:web:3b6e8818322437d26ba5c3',
    messagingSenderId: '766431108730',
    projectId: 'home-needer',
    authDomain: 'home-needer.firebaseapp.com',
    storageBucket: 'home-needer.appspot.com',
    measurementId: 'G-L1TK38FSNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd7PvuOQZvVcDXg357EdxXL0eQQZk7tfo',
    appId: '1:766431108730:android:8468b3cbf0bc2a356ba5c3',
    messagingSenderId: '766431108730',
    projectId: 'home-needer',
    storageBucket: 'home-needer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuqbNnfNefNyYbPVX-Mup_B9D_RDc9V8I',
    appId: '1:766431108730:ios:6085b99896c3f1266ba5c3',
    messagingSenderId: '766431108730',
    projectId: 'home-needer',
    storageBucket: 'home-needer.appspot.com',
    iosBundleId: 'com.example.homeNeeder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuqbNnfNefNyYbPVX-Mup_B9D_RDc9V8I',
    appId: '1:766431108730:ios:6085b99896c3f1266ba5c3',
    messagingSenderId: '766431108730',
    projectId: 'home-needer',
    storageBucket: 'home-needer.appspot.com',
    iosBundleId: 'com.example.homeNeeder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZClBjWbnkRa42reszgmFenQLyR04Fxys',
    appId: '1:766431108730:web:cef9bdd69e8722fa6ba5c3',
    messagingSenderId: '766431108730',
    projectId: 'home-needer',
    authDomain: 'home-needer.firebaseapp.com',
    storageBucket: 'home-needer.appspot.com',
    measurementId: 'G-JN94HP9T74',
  );
}
